parameters:
#    gy_admin.example.class: Gy\AdminBundle\Example

services:
#    gy_admin.example:
#        class: %gy_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
