Gy\CoreBundle\Document\Product:
    fields:
        id:
            id:  true
        gid:
            type: increment
        name:
            type: string
        chineseName:
            type: string
        isSerial:
            type: boolean
        cost:
            type: float
        price:
            type: collection
        description:
            type: string
        category:
            type: collection
        attributes:
            type: hash
        sold:
            type: int
        createdAt:
            type: date